# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcMainFrame(wx.Frame):
#!XRCED:begin-block:xrcMainFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcMainFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MainFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.fileChoice = xrc.XRCCTRL(self, "fileChoice")
        self.fileTreeCtrl = xrc.XRCCTRL(self, "fileTreeCtrl")
        self.signalListBox = xrc.XRCCTRL(self, "signalListBox")
        self.filterSearchCtrl = xrc.XRCCTRL(self, "filterSearchCtrl")
        self.viewNotebook = xrc.XRCCTRL(self, "viewNotebook")
        self.sweepListCtrl = xrc.XRCCTRL(self, "sweepListCtrl")

        self.Bind(wx.EVT_MENU, self.OnMenu_fileOpenMenuItem, id=xrc.XRCID('fileOpenMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_fileReloadMenuItem, id=xrc.XRCID('fileReloadMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_fileCloseMenuItem, id=xrc.XRCID('fileCloseMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_exitMenuItem, id=xrc.XRCID('exitMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_viewNewMenuItem, id=xrc.XRCID('viewNewMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_viewCloseMenuItem, id=xrc.XRCID('viewCloseMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_viewRenameMenuItem, id=xrc.XRCID('viewRenameMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_aboutMenuItem, id=xrc.XRCID('aboutMenuItem'))
        self.Bind(wx.EVT_TOOL, self.OnTool_fileOpenTool, id=xrc.XRCID('fileOpenTool'))
        self.Bind(wx.EVT_TOOL, self.OnTool_fileReloadTool, id=xrc.XRCID('fileReloadTool'))
        self.Bind(wx.EVT_TOOL, self.OnTool_fileCloseTool, id=xrc.XRCID('fileCloseTool'))
        self.Bind(wx.EVT_TOOL, self.OnTool_viewNewTool, id=xrc.XRCID('viewNewTool'))
        self.Bind(wx.EVT_TOOL, self.OnTool_viewCloseTool, id=xrc.XRCID('viewCloseTool'))
        self.Bind(wx.EVT_CHOICE, self.OnChoice_fileChoice, self.fileChoice)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.OnTree_sel_changed_fileTreeCtrl, self.fileTreeCtrl)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnListbox_dclick_signalListBox, self.signalListBox)
        self.Bind(wx.EVT_SEARCHCTRL_CANCEL_BTN, self.OnSearchctrl_cancel_btn_filterSearchCtrl, self.filterSearchCtrl)
        self.Bind(wx.EVT_TEXT, self.OnText_filterSearchCtrl, self.filterSearchCtrl)

#!XRCED:begin-block:xrcMainFrame.OnMenu_fileOpenMenuItem
    def OnMenu_fileOpenMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_fileOpenMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_fileOpenMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_fileReloadMenuItem
    def OnMenu_fileReloadMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_fileReloadMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_fileReloadMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_fileCloseMenuItem
    def OnMenu_fileCloseMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_fileCloseMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_fileCloseMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_exitMenuItem
    def OnMenu_exitMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_exitMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_exitMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_viewNewMenuItem
    def OnMenu_viewNewMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_viewNewMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_viewNewMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_viewCloseMenuItem
    def OnMenu_viewCloseMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_viewCloseMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_viewCloseMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_viewRenameMenuItem
    def OnMenu_viewRenameMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_viewRenameMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_viewRenameMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_aboutMenuItem
    def OnMenu_aboutMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_aboutMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_aboutMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnTool_fileOpenTool
    def OnTool_fileOpenTool(self, evt):
        # Replace with event handler code
        print "OnTool_fileOpenTool()"
#!XRCED:end-block:xrcMainFrame.OnTool_fileOpenTool        

#!XRCED:begin-block:xrcMainFrame.OnTool_fileReloadTool
    def OnTool_fileReloadTool(self, evt):
        # Replace with event handler code
        print "OnTool_fileReloadTool()"
#!XRCED:end-block:xrcMainFrame.OnTool_fileReloadTool        

#!XRCED:begin-block:xrcMainFrame.OnTool_fileCloseTool
    def OnTool_fileCloseTool(self, evt):
        # Replace with event handler code
        print "OnTool_fileCloseTool()"
#!XRCED:end-block:xrcMainFrame.OnTool_fileCloseTool        

#!XRCED:begin-block:xrcMainFrame.OnTool_viewNewTool
    def OnTool_viewNewTool(self, evt):
        # Replace with event handler code
        print "OnTool_viewNewTool()"
#!XRCED:end-block:xrcMainFrame.OnTool_viewNewTool        

#!XRCED:begin-block:xrcMainFrame.OnTool_viewCloseTool
    def OnTool_viewCloseTool(self, evt):
        # Replace with event handler code
        print "OnTool_viewCloseTool()"
#!XRCED:end-block:xrcMainFrame.OnTool_viewCloseTool        

#!XRCED:begin-block:xrcMainFrame.OnChoice_fileChoice
    def OnChoice_fileChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_fileChoice()"
#!XRCED:end-block:xrcMainFrame.OnChoice_fileChoice        

#!XRCED:begin-block:xrcMainFrame.OnTree_sel_changed_fileTreeCtrl
    def OnTree_sel_changed_fileTreeCtrl(self, evt):
        # Replace with event handler code
        print "OnTree_sel_changed_fileTreeCtrl()"
#!XRCED:end-block:xrcMainFrame.OnTree_sel_changed_fileTreeCtrl        

#!XRCED:begin-block:xrcMainFrame.OnListbox_dclick_signalListBox
    def OnListbox_dclick_signalListBox(self, evt):
        # Replace with event handler code
        print "OnListbox_dclick_signalListBox()"
#!XRCED:end-block:xrcMainFrame.OnListbox_dclick_signalListBox        

#!XRCED:begin-block:xrcMainFrame.OnSearchctrl_cancel_btn_filterSearchCtrl
    def OnSearchctrl_cancel_btn_filterSearchCtrl(self, evt):
        # Replace with event handler code
        print "OnSearchctrl_cancel_btn_filterSearchCtrl()"
#!XRCED:end-block:xrcMainFrame.OnSearchctrl_cancel_btn_filterSearchCtrl        

#!XRCED:begin-block:xrcMainFrame.OnText_filterSearchCtrl
    def OnText_filterSearchCtrl(self, evt):
        # Replace with event handler code
        print "OnText_filterSearchCtrl()"
#!XRCED:end-block:xrcMainFrame.OnText_filterSearchCtrl        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('pywave.xrc')
